echo src/*.sh
echo src/*.c
echo "*"
echo '*'
echo */*.h
echo */*.c
echo "*/*.h"
echo "*/*.c"
echo '*/*.h'
echo '*/*.c'
echo [24][21]sh
echo [24][21]"sh"
echo [24][21]'sh'
echo "[24][21]sh"
echo '[24][21]sh'
echo *
echo s?c ob? ???? ?
echo [!s]bj [!owf1-9]rc
echo src/[a-zA-Z]*.c
echo {src,obj}
echo {a,c,b}
echo {a}
echo */*/*.{h,c,o}
echo {src,obj}/*
echo {src,obj}/*/{h,c,o}
echo {src,obj}/*/*.{h,c,o}
echo {src,obj,}/*/*.{h,c,o}
echo {src,obj,include}/*/*.{h,c,o}
echo {{src,obj},include}/*/*.{h,c,o}
