empty heredoc << [✔]
empty heredoc <<- [✔]
multiple heredoc << [✔]
multiple heredoc <<- [✔]
heredoc subshell << [✔]
heredoc subshell <<- [✔]
heredoc multiple subshell << [✔]
heredoc multiple subshell <<- [✔]
