echo sdf${HOME}a${HOME}sdf sdf${HOME}a${HOME}sdf sdf${HOME}a${HOME}sdf
echo sdf${HOME} sdf${HOME} sdf${HOME} sdf${HOME}a${HOME}sdf sdf${HOME}a${HOME}sdf
echo ${HOME}
echo "sdf${HOME}"
echo "${HOME}"
echo sdf$HOME
echo $HOME
echo "sdf$HOME"
echo "$HOME"
echo sdf${HOME}${HOME}
echo ${HOME}${HOME}
echo "sdf${HOME}${HOME}"
echo "${HOME}${HOME}"
echo sdf$HOME$HOME
echo $HOME$HOME
echo "sdf$HOME$HOME"
echo "$HOME$HOME"
echo sdf${HOME}a${HOME}
echo ${HOME}b${HOME}
echo "sdf${HOME}c${HOME}"
echo "${HOME}d${HOME}"
echo sdf$HOMEe$HOME
echo $HOMEf$HOME
echo "sdf$HOMEg$HOME"
echo "$HOMEh$HOME"
echo ${HOME}b${HOME}sdf
echo "sdf${HOME}c${HOME}dfg"
echo "${HOME}d${HOME}fgh"
echo sdf$HOMEe$HOMEghj
echo $HOMEf$HOMEhjk
echo "sdf$HOMEg$HOMEhjkl"
echo "$HOMEh$HOMEhjkl"
echo sdf${OOPS}
echo ${OOPS}
echo "sdf${OOPS}"
echo "${OOPS}"
echo sdf$OOPS
echo $OOPS
echo "sdf$OOPS"
echo "$OOPS"
echo sdf${OOPS}${OOPS}
echo ${OOPS}${OOPS}
echo "sdf${OOPS}${OOPS}"
echo "${OOPS}${OOPS}"
echo sdf$OOPS$OOPS
echo $OOPS$OOPS
echo "sdf$OOPS$OOPS"
echo "$OOPS$OOPS"
echo sdf${OOPS}a${OOPS}
echo ${OOPS}b${OOPS}
echo "sdf${OOPS}c${OOPS}"
echo "${OOPS}d${OOPS}"
echo sdf$OOPSe$OOPS
echo $OOPSf$OOPS
echo "sdf$OOPSg$OOPS"
echo "$OOPSh$OOPS"
echo sdf${OOPS}a${OOPS}sdf
echo ${OOPS}b${OOPS}sdf
echo "sdf${OOPS}c${OOPS}dfg"
echo "${OOPS}d${OOPS}fgh"
echo sdf$OOPSe$OOPSghj
echo $OOPSf$OOPShjk
echo "sdf$OOPSg$OOPShjkl"
echo "$OOPSh$OOPShjkl"
